include:
- split/*
kind: ArchiveUploadSpec
name: split-ilO6

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: split-1aeb8a64-2286-4c49-841d-228de22f8afb
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: casapython
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://split-ilO6
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-05-05T10:46:47Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: split
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: casapython
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: split.main
    packageref:
      name: split-1aeb8a64-2286-4c49-841d-228de22f8afb
      namespace: default
  requestsPerPod: 1
  resources: {}
