include:
- fits2ms/*
kind: ArchiveUploadSpec
name: fits2ms-19wj

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fits2ms-4e22a21d-496e-4f1b-982b-2b369735e925
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: casapython
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://fits2ms-19wj
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-05-05T10:26:39Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fits2ms
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: casapython
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: fits2ms.main
    packageref:
      name: fits2ms-4e22a21d-496e-4f1b-982b-2b369735e925
      namespace: default
  requestsPerPod: 1
  resources: {}
