apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: applycal
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: applycal
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /applycal
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /applycal
