include:
- hello/*
kind: ArchiveUploadSpec
name: hello-5xAw

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: test-5ddaa581-9b7d-4719-8f2c-3341f3d1d86a
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: python2
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://hello-5xAw
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-04-12T09:26:40Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: test
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python2
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: hello.main
    packageref:
      name: test-5ddaa581-9b7d-4719-8f2c-3341f3d1d86a
      namespace: default
  requestsPerPod: 1
  resources: {}
