apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 468d424d-d498-42f8-9b8c-66dd336be46c
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: test
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /test
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /test
