include:
- aoflagger/*
kind: ArchiveUploadSpec
name: aoflagger-Wb2I

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: aoflagger-7f16ae66-5fde-4d0a-98e1-2772f81a0ef1
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: aoflagger-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://aoflagger-Wb2I
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-05-05T11:50:09Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: aoflagger
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: aoflagger-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: aoflagger.main
    packageref:
      name: aoflagger-7f16ae66-5fde-4d0a-98e1-2772f81a0ef1
      namespace: default
  requestsPerPod: 1
  resources: {}
