include:
- bandpasscal/*
kind: ArchiveUploadSpec
name: bandpasscal-OyHb

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: bandpasscal-3903c089-377f-4a36-8f32-a25e4cc7f311
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: casapython
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://bandpasscal-OyHb
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-04-27T17:31:36Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: bandpasscal
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: casapython
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: bandpasscal.main
    packageref:
      name: bandpasscal-3903c089-377f-4a36-8f32-a25e4cc7f311
      namespace: default
  requestsPerPod: 1
  resources: {}
