apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: f55d1e09-659b-4b12-ae19-83568d161ed1
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: listobs
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /listobs
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /listobs
