apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 63a7079a-e7ce-4a07-b8f9-d21a2a3f2a0f
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fits2ms
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /fits2ms
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /fits2ms
