include:
- hello/*
kind: ArchiveUploadSpec
name: hello-t3Yk

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: hello-spec-7b53bf36-9423-4c5f-ae16-f8825aa80422
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: casapy
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://hello-t3Yk
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-04-11T09:17:24Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: hello-spec
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: casapy
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: hello.main
    packageref:
      name: hello-spec-7b53bf36-9423-4c5f-ae16-f8825aa80422
      namespace: default
  requestsPerPod: 1
  resources: {}
