apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 0e86471c-7b5f-493f-98d5-2a7024f97bef
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: hello-spec
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /hello
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /hello
