include:
- hello/*
kind: ArchiveUploadSpec
name: hello-dMvs

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: hello-22766a29-b105-4af3-a51e-71c60bd8249f
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: casapy-spec
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://hello-dMvs
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-04-10T11:28:29Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: hello
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: casapy-spec
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: hello.main
    packageref:
      name: hello-22766a29-b105-4af3-a51e-71c60bd8249f
      namespace: default
  requestsPerPod: 1
  resources: {}
