apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: d3dec209-9226-4d34-ad12-32c82cc20787
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: hello
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /hello
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /hello
