name: build-docker-images

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Images
      run: |
        for file in $(find pipeline/ -name 'Dockerfile*'); do
          directory=$(dirname $file)
          if [[ "$directory" == "casa-"* ]]; then
            upperdir=$(dirname $directory)
            image_name=$(basename $upperdir)-$(basename $directory)
          else 
            image_name=$(basename $directory)
          docker build -t "$image_name" $directory
        done
