name: build-docker-images

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Images
      run: |
        for file in $(find pipeline/calibration -name 'Dockerfile*'); do
          directory=$(dirname $file)
          upperdir=$(dirname $directory)
          image_name=$(basename $upperdir)-$(basename $directory)
          docker build -t "$image_name" $directory
        done
